### ISSUE TITLE
Duplicate key events on Windows

### ISSUE THREAD

**Issue by target6404** [alejandroqh/term39#2]
All key events on Windows are registered twice, once on press and once on release. This is a known issue: https://github.com/ratatui/ratatui/issues/347

To fix, check `key_event.kind == KeyEventKind::Press` in every function that handles key events.

A more complete fix would be a refactor to handle all input in a centralized manner to avoid having to repeatedly apply this to new functionality.

**Comment by alejandroqh** [comment]
I found one problem 

<img width="317" height="208" alt="Image" src="https://github.com/user-attachments/assets/2384e822-c6f9-468e-a008-6c84c726a8ad" />

This click is not working as expected

**Comment by alejandroqh** [comment]
<img width="1000" height="580" alt="Image" src="https://github.com/user-attachments/assets/7df086e3-2f91-4680-ac8a-8bb5655c630b" /> I am testing it in Windows 10

**Comment by alejandroqh** [comment]
Thanks I will work on this right now, I have time

**Comment by alejandroqh** [comment]
I just released v0.16.5 please give a check if is working better for you.

**Comment by graphixillusion** [comment]
With version 0.16.5 the mouse click in the confirmation window works good but the lag when typing on the keyboard, expecially when you start to open multiple terminal windows is still present: the typing is not fluid and you need to press the key multiple times until it records the input.

**Comment by alejandroqh** [comment]
Ok thanks for confirming the buttons are working, ok I will give a check for lag with a real machine asap

**Comment by graphixillusion** [comment]
Yep, i've tried the 0.17.0 but the input is still not good, maybe a super little bit better than before but still hardly present sadly
